apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-1
  labels:
    app: nextcloud
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/kube/nextcloud"
