apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-config
  labels:
    app: nextcloud
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
