apiVersion: v1
kind: Pod
metadata:
  name: volume-example
spec:
  volumes:
    - name: host-volume
      persistentVolumeClaim:
        claimName: pvc-hostpath
  containers:
    - image: busybox
      name: volume-example
      command: ["/bin/sh"]
      args: ["-c", "sleep 600"]
      volumeMounts:
        - name: host-volume
          mountPath: /data
          subPath: sub
