apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./config/deployment.yaml
  - ./config/service.yaml
  - ./config/pv-0.yaml
  - ./config/pv-1.yaml
  - ./config/pvc-config.yaml
  - ./config/pvc-data.yaml

configMapGenerator:
  - name: nextcloud-env
    env: config/nextcloud.env
